### ISSUE TITLE
PlottingUtils Update

### ISSUE THREAD

**Issue by avcarr2** [avcarr2/FCWTNET#25]
Currently, there a Generate(typeofplot) method and then a GenerateCWT(typeofplot). So if you want to change one thing about a plot, you have to change several methods. Make one plot method per type of plot and use optional parameters and overloading to make methods that handle different subtypes of the same plot. 
*  [Example with heatmap](https://github.com/avcarr2/FCWTNET/blob/f4dfb6842f356466f743610df35d327a6a1eee01/FCWTAPI/PlottingUtils.cs#L46). 
* [Example with XYPlot](https://github.com/avcarr2/FCWTNET/blob/f4dfb6842f356466f743610df35d327a6a1eee01/FCWTAPI/PlottingUtils.cs#L141)

**Comment by zdanaceau** [comment]
Those GenerateCWT(typeofplot) methods are completely separate from the Generate(typeofplot) methods. I believe I made those latter just to figure out how to use OxyPlot so I'm just going to delete those since they are never used. I'll try to simplify the GenerateCWT(typeofplot) methods as much as I can though because I do feel that they're a bit clunky.

**Comment by zdanaceau** [comment]
Fixed this in #31.
